export default {
	BEVERAGES_PAGE_TITLE: 'Bebidas',
	BEVERAGES_ADD_BUTTON_TITLE: 'Adicionar',
	BEVERAGE_INSERT_DIALOG_TITLE: 'Adicionar bebida',
	BEVERAGE_UPDATE_DIALOG_TITLE: 'Editar bebida',
	BEVERAGE_SUBMIT_BUTTON_TITLE: 'Salvar',
	BEVERAGE_SUBMIT_ERROR_MESSAGE: 'Falha ao salvar bebida'
}
